CREATE OR REPLACE FUNCTION futures.upsert_ticks_raw()
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    rows_affected BIGINT;
BEGIN
    INSERT INTO futures.ticks_raw (
        symbol,
        month_key,
        date,
        time,
        sequence,
        depth_sequence,
        price,
        volume,
        trade_type,
        ask_price,
        bid_price,
        ask_size,
        bid_size,
        total_ask_depth,
        total_bid_depth,
        ask_dom_price,
        bid_dom_price,
        ask_dom_0,  bid_dom_0,
        ask_dom_1,  bid_dom_1,
        ask_dom_2,  bid_dom_2,
        ask_dom_3,  bid_dom_3,
        ask_dom_4,  bid_dom_4,
        ask_dom_5,  bid_dom_5,
        ask_dom_6,  bid_dom_6,
        ask_dom_7,  bid_dom_7,
        ask_dom_8,  bid_dom_8,
        ask_dom_9,  bid_dom_9,
        ask_dom_10, bid_dom_10,
        ask_dom_11, bid_dom_11,
        ask_dom_12, bid_dom_12,
        ask_dom_13, bid_dom_13,
        ask_dom_14, bid_dom_14,
        ask_dom_15, bid_dom_15,
        ask_dom_16, bid_dom_16,
        ask_dom_17, bid_dom_17,
        ask_dom_18, bid_dom_18,
        ask_dom_19, bid_dom_19,
        ask_dom_20, bid_dom_20,
        ask_dom_21, bid_dom_21,
        ask_dom_22, bid_dom_22,
        ask_dom_23, bid_dom_23,
        ask_dom_24, bid_dom_24,
        ask_dom_25, bid_dom_25,
        ask_dom_26, bid_dom_26,
        ask_dom_27, bid_dom_27,
        ask_dom_28, bid_dom_28,
        ask_dom_29, bid_dom_29
    )
    SELECT
        symbol,
        month_key,
        date,
        time,
        sequence,
        depth_sequence,
        price,
        volume,
        trade_type,
        ask_price,
        bid_price,
        ask_size,
        bid_size,
        total_ask_depth,
        total_bid_depth,
        ask_dom_price,
        bid_dom_price,
        ask_dom_0,  bid_dom_0,
        ask_dom_1,  bid_dom_1,
        ask_dom_2,  bid_dom_2,
        ask_dom_3,  bid_dom_3,
        ask_dom_4,  bid_dom_4,
        ask_dom_5,  bid_dom_5,
        ask_dom_6,  bid_dom_6,
        ask_dom_7,  bid_dom_7,
        ask_dom_8,  bid_dom_8,
        ask_dom_9,  bid_dom_9,
        ask_dom_10, bid_dom_10,
        ask_dom_11, bid_dom_11,
        ask_dom_12, bid_dom_12,
        ask_dom_13, bid_dom_13,
        ask_dom_14, bid_dom_14,
        ask_dom_15, bid_dom_15,
        ask_dom_16, bid_dom_16,
        ask_dom_17, bid_dom_17,
        ask_dom_18, bid_dom_18,
        ask_dom_19, bid_dom_19,
        ask_dom_20, bid_dom_20,
        ask_dom_21, bid_dom_21,
        ask_dom_22, bid_dom_22,
        ask_dom_23, bid_dom_23,
        ask_dom_24, bid_dom_24,
        ask_dom_25, bid_dom_25,
        ask_dom_26, bid_dom_26,
        ask_dom_27, bid_dom_27,
        ask_dom_28, bid_dom_28,
        ask_dom_29, bid_dom_29
    FROM futures.staging_ticks_raw
    ON CONFLICT (symbol, month_key, date, time, sequence)
    DO UPDATE SET
        depth_sequence  = EXCLUDED.depth_sequence,
        price           = EXCLUDED.price,
        volume          = EXCLUDED.volume,
        trade_type      = EXCLUDED.trade_type,
        ask_price       = EXCLUDED.ask_price,
        bid_price       = EXCLUDED.bid_price,
        ask_size        = EXCLUDED.ask_size,
        bid_size        = EXCLUDED.bid_size,
        total_ask_depth = EXCLUDED.total_ask_depth,
        total_bid_depth = EXCLUDED.total_bid_depth,
        ask_dom_price   = EXCLUDED.ask_dom_price,
        bid_dom_price   = EXCLUDED.bid_dom_price,
        ask_dom_0  = EXCLUDED.ask_dom_0,  bid_dom_0  = EXCLUDED.bid_dom_0,
        ask_dom_1  = EXCLUDED.ask_dom_1,  bid_dom_1  = EXCLUDED.bid_dom_1,
        ask_dom_2  = EXCLUDED.ask_dom_2,  bid_dom_2  = EXCLUDED.bid_dom_2,
        ask_dom_3  = EXCLUDED.ask_dom_3,  bid_dom_3  = EXCLUDED.bid_dom_3,
        ask_dom_4  = EXCLUDED.ask_dom_4,  bid_dom_4  = EXCLUDED.bid_dom_4,
        ask_dom_5  = EXCLUDED.ask_dom_5,  bid_dom_5  = EXCLUDED.bid_dom_5,
        ask_dom_6  = EXCLUDED.ask_dom_6,  bid_dom_6  = EXCLUDED.bid_dom_6,
        ask_dom_7  = EXCLUDED.ask_dom_7,  bid_dom_7  = EXCLUDED.bid_dom_7,
        ask_dom_8  = EXCLUDED.ask_dom_8,  bid_dom_8  = EXCLUDED.bid_dom_8,
        ask_dom_9  = EXCLUDED.ask_dom_9,  bid_dom_9  = EXCLUDED.bid_dom_9,
        ask_dom_10 = EXCLUDED.ask_dom_10, bid_dom_10 = EXCLUDED.bid_dom_10,
        ask_dom_11 = EXCLUDED.ask_dom_11, bid_dom_11 = EXCLUDED.bid_dom_11,
        ask_dom_12 = EXCLUDED.ask_dom_12, bid_dom_12 = EXCLUDED.bid_dom_12,
        ask_dom_13 = EXCLUDED.ask_dom_13, bid_dom_13 = EXCLUDED.bid_dom_13,
        ask_dom_14 = EXCLUDED.ask_dom_14, bid_dom_14 = EXCLUDED.bid_dom_14,
        ask_dom_15 = EXCLUDED.ask_dom_15, bid_dom_15 = EXCLUDED.bid_dom_15,
        ask_dom_16 = EXCLUDED.ask_dom_16, bid_dom_16 = EXCLUDED.bid_dom_16,
        ask_dom_17 = EXCLUDED.ask_dom_17, bid_dom_17 = EXCLUDED.bid_dom_17,
        ask_dom_18 = EXCLUDED.ask_dom_18, bid_dom_18 = EXCLUDED.bid_dom_18,
        ask_dom_19 = EXCLUDED.ask_dom_19, bid_dom_19 = EXCLUDED.bid_dom_19,
        ask_dom_20 = EXCLUDED.ask_dom_20, bid_dom_20 = EXCLUDED.bid_dom_20,
        ask_dom_21 = EXCLUDED.ask_dom_21, bid_dom_21 = EXCLUDED.bid_dom_21,
        ask_dom_22 = EXCLUDED.ask_dom_22, bid_dom_22 = EXCLUDED.bid_dom_22,
        ask_dom_23 = EXCLUDED.ask_dom_23, bid_dom_23 = EXCLUDED.bid_dom_23,
        ask_dom_24 = EXCLUDED.ask_dom_24, bid_dom_24 = EXCLUDED.bid_dom_24,
        ask_dom_25 = EXCLUDED.ask_dom_25, bid_dom_25 = EXCLUDED.bid_dom_25,
        ask_dom_26 = EXCLUDED.ask_dom_26, bid_dom_26 = EXCLUDED.bid_dom_26,
        ask_dom_27 = EXCLUDED.ask_dom_27, bid_dom_27 = EXCLUDED.bid_dom_27,
        ask_dom_28 = EXCLUDED.ask_dom_28, bid_dom_28 = EXCLUDED.bid_dom_28,
        ask_dom_29 = EXCLUDED.ask_dom_29, bid_dom_29 = EXCLUDED.bid_dom_29,
        updated_at = NOW();

    GET DIAGNOSTICS rows_affected = ROW_COUNT;
    RETURN rows_affected;
END;
$$;
