CREATE TABLE futures.staging_ticks_raw (
    symbol          VARCHAR(10)     NOT NULL,
    month_key       VARCHAR(6)      NOT NULL,
    date            DATE            NOT NULL,
    time            TIME(3)         NOT NULL,
    sequence        BIGINT          NOT NULL,
    depth_sequence  BIGINT,
    price           DOUBLE PRECISION,
    volume          INTEGER,
    trade_type      SMALLINT,
    ask_price       DOUBLE PRECISION,
    bid_price       DOUBLE PRECISION,
    ask_size        INTEGER,
    bid_size        INTEGER,
    total_ask_depth INTEGER,
    total_bid_depth INTEGER,
    ask_dom_price   DOUBLE PRECISION,
    bid_dom_price   DOUBLE PRECISION,
    ask_dom_0       INTEGER,  bid_dom_0  INTEGER,
    ask_dom_1       INTEGER,  bid_dom_1  INTEGER,
    ask_dom_2       INTEGER,  bid_dom_2  INTEGER,
    ask_dom_3       INTEGER,  bid_dom_3  INTEGER,
    ask_dom_4       INTEGER,  bid_dom_4  INTEGER,
    ask_dom_5       INTEGER,  bid_dom_5  INTEGER,
    ask_dom_6       INTEGER,  bid_dom_6  INTEGER,
    ask_dom_7       INTEGER,  bid_dom_7  INTEGER,
    ask_dom_8       INTEGER,  bid_dom_8  INTEGER,
    ask_dom_9       INTEGER,  bid_dom_9  INTEGER,
    ask_dom_10      INTEGER,  bid_dom_10 INTEGER,
    ask_dom_11      INTEGER,  bid_dom_11 INTEGER,
    ask_dom_12      INTEGER,  bid_dom_12 INTEGER,
    ask_dom_13      INTEGER,  bid_dom_13 INTEGER,
    ask_dom_14      INTEGER,  bid_dom_14 INTEGER,
    ask_dom_15      INTEGER,  bid_dom_15 INTEGER,
    ask_dom_16      INTEGER,  bid_dom_16 INTEGER,
    ask_dom_17      INTEGER,  bid_dom_17 INTEGER,
    ask_dom_18      INTEGER,  bid_dom_18 INTEGER,
    ask_dom_19      INTEGER,  bid_dom_19 INTEGER,
    ask_dom_20      INTEGER,  bid_dom_20 INTEGER,
    ask_dom_21      INTEGER,  bid_dom_21 INTEGER,
    ask_dom_22      INTEGER,  bid_dom_22 INTEGER,
    ask_dom_23      INTEGER,  bid_dom_23 INTEGER,
    ask_dom_24      INTEGER,  bid_dom_24 INTEGER,
    ask_dom_25      INTEGER,  bid_dom_25 INTEGER,
    ask_dom_26      INTEGER,  bid_dom_26 INTEGER,
    ask_dom_27      INTEGER,  bid_dom_27 INTEGER,
    ask_dom_28      INTEGER,  bid_dom_28 INTEGER,
    ask_dom_29      INTEGER,  bid_dom_29 INTEGER
)