CREATE OR REPLACE FUNCTION futures.upsert_ticks_enriched()
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    rows_affected BIGINT;
BEGIN
    INSERT INTO futures.ticks_enriched (
        symbol,
        month_key,
        "Date",
        "Time",
        "Sequence",
        "DepthSequence",
        "Price",
        "Volume",
        "TradeType",
        "AskPrice",
        "BidPrice",
        "AskSize",
        "BidSize",
        "TotalAskDepth",
        "TotalBidDepth",
        "AskDOMPrice",
        "BidDOMPrice",
        "AskDOM_0",  "BidDOM_0",
        "AskDOM_1",  "BidDOM_1",
        "AskDOM_2",  "BidDOM_2",
        "AskDOM_3",  "BidDOM_3",
        "AskDOM_4",  "BidDOM_4",
        "AskDOM_5",  "BidDOM_5",
        "AskDOM_6",  "BidDOM_6",
        "AskDOM_7",  "BidDOM_7",
        "AskDOM_8",  "BidDOM_8",
        "AskDOM_9",  "BidDOM_9",
        "AskDOM_10", "BidDOM_10",
        "AskDOM_11", "BidDOM_11",
        "AskDOM_12", "BidDOM_12",
        "AskDOM_13", "BidDOM_13",
        "AskDOM_14", "BidDOM_14",
        "AskDOM_15", "BidDOM_15",
        "AskDOM_16", "BidDOM_16",
        "AskDOM_17", "BidDOM_17",
        "AskDOM_18", "BidDOM_18",
        "AskDOM_19", "BidDOM_19",
        "AskDOM_20", "BidDOM_20",
        "AskDOM_21", "BidDOM_21",
        "AskDOM_22", "BidDOM_22",
        "AskDOM_23", "BidDOM_23",
        "AskDOM_24", "BidDOM_24",
        "AskDOM_25", "BidDOM_25",
        "AskDOM_26", "BidDOM_26",
        "AskDOM_27", "BidDOM_27",
        "AskDOM_28", "BidDOM_28",
        "AskDOM_29", "BidDOM_29",
        "Datetime",
        "Hour",
        "SessionType",
        "POC",
        "Prev_POC",
        "VA_Areas",
        "ValleysPeaks",
        "CD_Ask",
        "CD_Bid",
        "CD_Total",
        "Session_High",
        "Session_Low",
        "Node_Volume",
        "Node_Ask_Volume",
        "Node_Bid_Volume",
        "Session_Volume",
        "LVN",
        "Index",
        current_bar_open,
        current_bar_high,
        current_bar_low,
        current_bar_close,
        current_bar_volume,
        current_bar_numberoftrades,
        current_bar_askvolume,
        current_bar_bidvolume,
        current_bar_datetime,
        next_bar_datetime,
        next_bar_open,
        next_bar_high,
        next_bar_low,
        next_bar_close,
        next_bar_volume,
        next_bar_num_trades,
        next_bar_ask_volume,
        next_bar_bid_volume,
        vwap,
        vwap_sd1_top,
        vwap_sd1_bottom,
        vwap_sd2_top,
        vwap_sd2_bottom,
        vwap_sd3_top,
        vwap_sd3_bottom,
        vwap_sd4_top,
        vwap_sd4_bottom
    )
    SELECT
        symbol,
        month_key,
        "Date",
        "Time",
        "Sequence",
        "DepthSequence",
        "Price",
        "Volume",
        "TradeType",
        "AskPrice",
        "BidPrice",
        "AskSize",
        "BidSize",
        "TotalAskDepth",
        "TotalBidDepth",
        "AskDOMPrice",
        "BidDOMPrice",
        "AskDOM_0",  "BidDOM_0",
        "AskDOM_1",  "BidDOM_1",
        "AskDOM_2",  "BidDOM_2",
        "AskDOM_3",  "BidDOM_3",
        "AskDOM_4",  "BidDOM_4",
        "AskDOM_5",  "BidDOM_5",
        "AskDOM_6",  "BidDOM_6",
        "AskDOM_7",  "BidDOM_7",
        "AskDOM_8",  "BidDOM_8",
        "AskDOM_9",  "BidDOM_9",
        "AskDOM_10", "BidDOM_10",
        "AskDOM_11", "BidDOM_11",
        "AskDOM_12", "BidDOM_12",
        "AskDOM_13", "BidDOM_13",
        "AskDOM_14", "BidDOM_14",
        "AskDOM_15", "BidDOM_15",
        "AskDOM_16", "BidDOM_16",
        "AskDOM_17", "BidDOM_17",
        "AskDOM_18", "BidDOM_18",
        "AskDOM_19", "BidDOM_19",
        "AskDOM_20", "BidDOM_20",
        "AskDOM_21", "BidDOM_21",
        "AskDOM_22", "BidDOM_22",
        "AskDOM_23", "BidDOM_23",
        "AskDOM_24", "BidDOM_24",
        "AskDOM_25", "BidDOM_25",
        "AskDOM_26", "BidDOM_26",
        "AskDOM_27", "BidDOM_27",
        "AskDOM_28", "BidDOM_28",
        "AskDOM_29", "BidDOM_29",
        "Datetime",
        "Hour",
        "SessionType",
        "POC",
        "Prev_POC",
        "VA_Areas",
        "ValleysPeaks",
        "CD_Ask",
        "CD_Bid",
        "CD_Total",
        "Session_High",
        "Session_Low",
        "Node_Volume",
        "Node_Ask_Volume",
        "Node_Bid_Volume",
        "Session_Volume",
        "LVN",
        "Index",
        current_bar_open,
        current_bar_high,
        current_bar_low,
        current_bar_close,
        current_bar_volume,
        current_bar_numberoftrades,
        current_bar_askvolume,
        current_bar_bidvolume,
        current_bar_datetime,
        next_bar_datetime,
        next_bar_open,
        next_bar_high,
        next_bar_low,
        next_bar_close,
        next_bar_volume,
        next_bar_num_trades,
        next_bar_ask_volume,
        next_bar_bid_volume,
        vwap,
        vwap_sd1_top,
        vwap_sd1_bottom,
        vwap_sd2_top,
        vwap_sd2_bottom,
        vwap_sd3_top,
        vwap_sd3_bottom,
        vwap_sd4_top,
        vwap_sd4_bottom
    FROM futures.staging_ticks_enriched
    ON CONFLICT (symbol, month_key, "Date", "Time", "Sequence")
    DO UPDATE SET
        "DepthSequence"            = EXCLUDED."DepthSequence",
        "Price"                    = EXCLUDED."Price",
        "Volume"                   = EXCLUDED."Volume",
        "TradeType"                = EXCLUDED."TradeType",
        "AskPrice"                 = EXCLUDED."AskPrice",
        "BidPrice"                 = EXCLUDED."BidPrice",
        "AskSize"                  = EXCLUDED."AskSize",
        "BidSize"                  = EXCLUDED."BidSize",
        "TotalAskDepth"            = EXCLUDED."TotalAskDepth",
        "TotalBidDepth"            = EXCLUDED."TotalBidDepth",
        "AskDOMPrice"              = EXCLUDED."AskDOMPrice",
        "BidDOMPrice"              = EXCLUDED."BidDOMPrice",
        "AskDOM_0"  = EXCLUDED."AskDOM_0",  "BidDOM_0"  = EXCLUDED."BidDOM_0",
        "AskDOM_1"  = EXCLUDED."AskDOM_1",  "BidDOM_1"  = EXCLUDED."BidDOM_1",
        "AskDOM_2"  = EXCLUDED."AskDOM_2",  "BidDOM_2"  = EXCLUDED."BidDOM_2",
        "AskDOM_3"  = EXCLUDED."AskDOM_3",  "BidDOM_3"  = EXCLUDED."BidDOM_3",
        "AskDOM_4"  = EXCLUDED."AskDOM_4",  "BidDOM_4"  = EXCLUDED."BidDOM_4",
        "AskDOM_5"  = EXCLUDED."AskDOM_5",  "BidDOM_5"  = EXCLUDED."BidDOM_5",
        "AskDOM_6"  = EXCLUDED."AskDOM_6",  "BidDOM_6"  = EXCLUDED."BidDOM_6",
        "AskDOM_7"  = EXCLUDED."AskDOM_7",  "BidDOM_7"  = EXCLUDED."BidDOM_7",
        "AskDOM_8"  = EXCLUDED."AskDOM_8",  "BidDOM_8"  = EXCLUDED."BidDOM_8",
        "AskDOM_9"  = EXCLUDED."AskDOM_9",  "BidDOM_9"  = EXCLUDED."BidDOM_9",
        "AskDOM_10" = EXCLUDED."AskDOM_10", "BidDOM_10" = EXCLUDED."BidDOM_10",
        "AskDOM_11" = EXCLUDED."AskDOM_11", "BidDOM_11" = EXCLUDED."BidDOM_11",
        "AskDOM_12" = EXCLUDED."AskDOM_12", "BidDOM_12" = EXCLUDED."BidDOM_12",
        "AskDOM_13" = EXCLUDED."AskDOM_13", "BidDOM_13" = EXCLUDED."BidDOM_13",
        "AskDOM_14" = EXCLUDED."AskDOM_14", "BidDOM_14" = EXCLUDED."BidDOM_14",
        "AskDOM_15" = EXCLUDED."AskDOM_15", "BidDOM_15" = EXCLUDED."BidDOM_15",
        "AskDOM_16" = EXCLUDED."AskDOM_16", "BidDOM_16" = EXCLUDED."BidDOM_16",
        "AskDOM_17" = EXCLUDED."AskDOM_17", "BidDOM_17" = EXCLUDED."BidDOM_17",
        "AskDOM_18" = EXCLUDED."AskDOM_18", "BidDOM_18" = EXCLUDED."BidDOM_18",
        "AskDOM_19" = EXCLUDED."AskDOM_19", "BidDOM_19" = EXCLUDED."BidDOM_19",
        "AskDOM_20" = EXCLUDED."AskDOM_20", "BidDOM_20" = EXCLUDED."BidDOM_20",
        "AskDOM_21" = EXCLUDED."AskDOM_21", "BidDOM_21" = EXCLUDED."BidDOM_21",
        "AskDOM_22" = EXCLUDED."AskDOM_22", "BidDOM_22" = EXCLUDED."BidDOM_22",
        "AskDOM_23" = EXCLUDED."AskDOM_23", "BidDOM_23" = EXCLUDED."BidDOM_23",
        "AskDOM_24" = EXCLUDED."AskDOM_24", "BidDOM_24" = EXCLUDED."BidDOM_24",
        "AskDOM_25" = EXCLUDED."AskDOM_25", "BidDOM_25" = EXCLUDED."BidDOM_25",
        "AskDOM_26" = EXCLUDED."AskDOM_26", "BidDOM_26" = EXCLUDED."BidDOM_26",
        "AskDOM_27" = EXCLUDED."AskDOM_27", "BidDOM_27" = EXCLUDED."BidDOM_27",
        "AskDOM_28" = EXCLUDED."AskDOM_28", "BidDOM_28" = EXCLUDED."BidDOM_28",
        "AskDOM_29" = EXCLUDED."AskDOM_29", "BidDOM_29" = EXCLUDED."BidDOM_29",
        "Datetime"             = EXCLUDED."Datetime",
        "Hour"                 = EXCLUDED."Hour",
        "SessionType"          = EXCLUDED."SessionType",
        "POC"                  = EXCLUDED."POC",
        "Prev_POC"             = EXCLUDED."Prev_POC",
        "VA_Areas"             = EXCLUDED."VA_Areas",
        "ValleysPeaks"         = EXCLUDED."ValleysPeaks",
        "CD_Ask"               = EXCLUDED."CD_Ask",
        "CD_Bid"               = EXCLUDED."CD_Bid",
        "CD_Total"             = EXCLUDED."CD_Total",
        "Session_High"         = EXCLUDED."Session_High",
        "Session_Low"          = EXCLUDED."Session_Low",
        "Node_Volume"          = EXCLUDED."Node_Volume",
        "Node_Ask_Volume"      = EXCLUDED."Node_Ask_Volume",
        "Node_Bid_Volume"      = EXCLUDED."Node_Bid_Volume",
        "Session_Volume"       = EXCLUDED."Session_Volume",
        "LVN"                  = EXCLUDED."LVN",
        "Index"                = EXCLUDED."Index",
        current_bar_open            = EXCLUDED.current_bar_open,
        current_bar_high            = EXCLUDED.current_bar_high,
        current_bar_low             = EXCLUDED.current_bar_low,
        current_bar_close           = EXCLUDED.current_bar_close,
        current_bar_volume          = EXCLUDED.current_bar_volume,
        current_bar_numberoftrades  = EXCLUDED.current_bar_numberoftrades,
        current_bar_askvolume       = EXCLUDED.current_bar_askvolume,
        current_bar_bidvolume       = EXCLUDED.current_bar_bidvolume,
        current_bar_datetime        = EXCLUDED.current_bar_datetime,
        next_bar_datetime           = EXCLUDED.next_bar_datetime,
        next_bar_open               = EXCLUDED.next_bar_open,
        next_bar_high               = EXCLUDED.next_bar_high,
        next_bar_low                = EXCLUDED.next_bar_low,
        next_bar_close              = EXCLUDED.next_bar_close,
        next_bar_volume             = EXCLUDED.next_bar_volume,
        next_bar_num_trades         = EXCLUDED.next_bar_num_trades,
        next_bar_ask_volume         = EXCLUDED.next_bar_ask_volume,
        next_bar_bid_volume         = EXCLUDED.next_bar_bid_volume,
        vwap                        = EXCLUDED.vwap,
        vwap_sd1_top                = EXCLUDED.vwap_sd1_top,
        vwap_sd1_bottom             = EXCLUDED.vwap_sd1_bottom,
        vwap_sd2_top                = EXCLUDED.vwap_sd2_top,
        vwap_sd2_bottom             = EXCLUDED.vwap_sd2_bottom,
        vwap_sd3_top                = EXCLUDED.vwap_sd3_top,
        vwap_sd3_bottom             = EXCLUDED.vwap_sd3_bottom,
        vwap_sd4_top                = EXCLUDED.vwap_sd4_top,
        vwap_sd4_bottom             = EXCLUDED.vwap_sd4_bottom,
        updated_at                  = NOW();

    GET DIAGNOSTICS rows_affected = ROW_COUNT;
    RETURN rows_affected;
END;
$$;
